// === DATA KOST dari kostjakarta.com ===
// Kebayoran Baru + Tanah Abang + Setiabudi
// Sorted: terdekat ke terjauh dari Gedung IDX
// Auto-generated

const ALL_KOST = [
    {
        no: 1,
        nama: "AbdiHome Kost Abdi Tendean Residence",
        alamat: "Gg. Jati No.47 A, RT.10/RW.1, Mampang Prpt., Kec. Mampang Prpt., Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12790",
        harga: "Tipe A Single KM Luar Jendela Rp. 1.700.000 Tipe B Single KM Dalam Jendela Rp. 2.180.000 Tipe C Double KM Dalam Jendela ",
        tipe: "Campur",
        kontak: "087778500955",
        fasilitas: "AC Kasur Bantal Guling Meja Kursi Lemari Baju Cermin Laci Ambalan Dinding Jendela Koridor/Keluar Fasilitas Kamar Mandi: KM Dalam / KM Luar Closet Duduk Wastafel Shower Water Heater Exhaust Fan",
        fasUmum: "Jaringan internet dan sinyal Wifi Dapur Kulkas Dispenser R. Jemur Jemuran Mesin Cuci Dryer Penjaga Kos CCTV Tangga Smart Lock Rooftop Fasilitas Parkir: Parkir Motor Parkir Sepeda",
        ukuran: "3 x 3",
        jumlah: "42",
        lat: -6.2345, lng: 106.8185,
        jarakIDX: 1.5,
        tanggal: "2026-02-21",
        narasi: "Sadon, ini paling deket ke kantor — cuma 1.5 km. Enaknya: ada Smart Lock, Rooftop, Mesin Cuci + Dryer sendiri. Mulai 1.7jt (KM luar) sampai 2.7jt (KM dalam). Ga enaknya: kamarnya standar 3x3, dan karena 42 kamar jadi rame. Tapi buat hemat waktu commute, ini juaranya. Pagi bisa ojol 5 menit udah sampe kantor.",
        fotos: ["https://www.kostjakarta.com/iklan/images/2026/02/7057_1.jpg", "https://www.kostjakarta.com/iklan/images/2026/02/7057_2.jpg", "https://www.kostjakarta.com/iklan/images/2026/02/7057_3.jpg", "https://www.kostjakarta.com/iklan/images/2026/02/7057_4.jpg"],
        foto: "https://www.kostjakarta.com/iklan/images/2026/02/7057_1.jpg",
    },
    {
        no: 2,
        nama: "Toba Mansion by AbdiHome",
        alamat: "Jl. Danau Toba No. 136, RT. 14 / RW. 3, Bendungan Hilir, Tanah Abang, Jakarta Pusat 10210",
        harga: "Rate Bulanan : Standard Single Rp. 3.500.000 Single Balkon Rp. 3.750.000 Single Deluxe Rp. 4.080.000 Standard Double Rp.",
        tipe: "Campur",
        kontak: "087778500955",
        fasilitas: "AC Bantal Cermin Guling Kasur Kursi Lemari Baju Meja TV Ventilasi Wastafel Water Heater Jendela Balkon / Non Balkon Fasilitas kamar mandi Air panas K. Mandi Dalam Kloset Duduk Shower Wastafel",
        fasUmum: "Wifi Air Jernih CCTV TV Dapur Dispenser Jemuran Kompor Kulkas Laundry 30kg/bulan Locker Meja Umum Mesin Cuci R. Cuci R. Jemur R. Tamu Taman Pengurus Kos Penjaga Kos Fasilitas parkir Parkir Mobil (+300rb/bulan) Parkir Motor Parkir Sepeda",
        ukuran: "3 x 3",
        jumlah: "18",
        lat: -6.21, lng: 106.815,
        jarakIDX: 1.7,
        tanggal: "2025-12-08",
        narasi: "Ini enak Sadon, udah include laundry 30kg/bulan — ga perlu keluar duit laundry lagi. Kamar ada TV, AC, Water Heater. Ada taman dan ruang tamu. Tapi harganya lumayan: mulai 3.5jt. Terus listrik token bayar sendiri. Lokasi Benhil, deket MRT. Kalau budget Sadon cukup dan mau yang udah serba include, ini oke.",
        fotos: ["https://kostjakarta.com/iklan/images/2025/11/7000_1.jpg", "https://kostjakarta.com/iklan/images/2025/11/7000_2.jpg", "https://kostjakarta.com/iklan/images/2025/11/7000_3.jpg", "https://kostjakarta.com/iklan/images/2025/11/7000_4.jpg"],
        foto: "https://kostjakarta.com/iklan/images/2025/11/7000_1.jpg",
    },
    {
        no: 3,
        nama: "Kost Bob 66",
        alamat: "Jl. Danau Di Bawah No. 66, RT.12 RW.03, Kel. Bendungan Hilir, Kec. Tanah Abang, Jakarta Pusat (10210)",
        harga: "Rp. 1.700.000 / bulan",
        tipe: "Pria (Karyawan)",
        kontak: "XXX",
        fasilitas: "Harga diatas sudah termasuk fasilitas : AC, WiFi, Listrik non Token 450 W, Tempat Tidur, Lemari Pakaian, Meja & Kursi, Kamar mandi luar.",
        fasUmum: "Kamar mandi luar kamar di lantai 2, Membawa Magic Jar, Sound System besar, Seteriska, tambah biaya listrik Rp. 150.000/bln",
        ukuran: "3 x 4 meter atap miring, kamar mandi luar",
        jumlah: "1",
        lat: -6.21, lng: 106.815,
        jarakIDX: 1.7,
        tanggal: "2025-12-05",
        narasi: "Jujur Sadon, ini murah (1.7jt) tapi basic banget. Kamar mandi luar, listrik cuma 450W (hati-hati kalau nyalain banyak barang). Kelebihannya: AC, WiFi udah include, dan lokasinya deket Sudirman (1 km). Cuma 1 kamar sisa, jadi kalau tertarik harus cepet. Ga cocok kalau Sadon butuh kenyamanan, tapi cocok kalau mau super hemat.",
        fotos: [],
        foto: "",
    },
    {
        no: 4,
        nama: "Kos Benhil Annapurna by AbdiHome",
        alamat: "Jl. D. Tamblingan No. 49, Rw. 3, Bendungan Hilir, Tanah Abang, Jakarta Pusat 10210",
        harga: "Rate / bulan: Tipe A Rp. 2.530.000 Tipe B Rp. 2.430.000 Tipe C Non Jendela Rp. 2.400.000 Tipe C Jendela Rp. 2.550.000 De",
        tipe: "Campur",
        kontak: "087778500955",
        fasilitas: "WiFi Kasur ortopedic 100×200 cm Lemari Meja Kursi AC Daikin Kamar mandi dalam Toilet duduk Shower Water Heater",
        fasUmum: "Kulkas Kompor Cooker Hood Tabung Gas Dispenser Mesin Cuci Parkiran motor depan kosan Penjaga Kos",
        ukuran: "3 x 3",
        jumlah: "31",
        lat: -6.21, lng: 106.815,
        jarakIDX: 1.7,
        tanggal: "2025-12-01",
        narasi: "Nah ini aku suka buat Sadon. AC-nya Daikin (hemat listrik, dingin), kasurnya ortopedic — tidur bakal nyenyak. Harga 2.4-2.5jt, pas di budget. Deket banget ke MRT Setiabudi, tinggal jalan 10 menit. Minusnya: kamar 3x3 agak kecil, dan ga ada laundry — harus ke luar. Tapi overall value-nya bagus.",
        fotos: ["https://kostjakarta.com/iklan/images/2025/11/6996_1.jpg", "https://kostjakarta.com/iklan/images/2025/11/6996_2.jpg", "https://kostjakarta.com/iklan/images/2025/11/6996_3.jpg", "https://kostjakarta.com/iklan/images/2025/11/6996_4.jpg"],
        foto: "https://kostjakarta.com/iklan/images/2025/11/6996_1.jpg",
    },
    {
        no: 5,
        nama: "Bunda Homestay",
        alamat: "Jl. Tanah Abang IV No.49, Rt.8/Rw.4, Petojo Selatan, Gambir, Kecamatan Gambir, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10160 – https://maps.",
        harga: "Per hari = Rp 100.000,- sd 125.000 Per minggu =Rp 850.000,- sd Rp 950.000 Perbulan : Rp 1.700.000,- single bed Rp 1.950.",
        tipe: "Pria / Wanita / Pasutri yang nikah & tercatat di KUA",
        kontak: "08111829599",
        fasilitas: "Gratis 3 modem Wi-Fi 4G LTE / Internet First Media TV Cable LED 19″ First Media / Indovision dinding Bricket AC 1 PK Inverter Sharp, kipas angin Kamar mandi dalam, water heater, water treatment, sliding shower/closet set, kitchen sink tap Inventaris ",
        fasUmum: "Kamar mandi umum, area parkir / cuci kendaraan roda 2 dan 4 gratis, Musholla, ruang tamu / tunggu, tempat jemur pakaian, tempat sampah & alas kaki.",
        ukuran: "3,5 m × 4 m 3,5 m × 5,5 m 3,5 m × 6,5 m 3,5 m × 8 m 3,5 mx 1",
        jumlah: "21",
        lat: -6.21, lng: 106.815,
        jarakIDX: 1.7,
        tanggal: "2025-07-24",
        narasi: "Ini unik Sadon — kayak tinggal di rumah keluarga. Kamarnya macem-macem ukuran, paling gede 3.5x10.5m (luas banget!). Fasilitas lengkap: First Media, AC Inverter, Water Treatment. Tapi aturannya ketat — harus pasutri tercatat KUA kalau berdua. Dekat Stasiun Tanah Abang. Cocok kalau Sadon mau suasana homey, ga cocok kalau mau yang modern/minimalis.",
        fotos: ["https://www.kostjakarta.com/iklan/images/2025/07/6904_1.jpg", "https://www.kostjakarta.com/iklan/images/2025/07/6904_2.jpg", "https://www.kostjakarta.com/iklan/images/2025/07/6904_3.jpg", "https://www.kostjakarta.com/iklan/images/2025/07/6904_4.jpg"],
        foto: "https://www.kostjakarta.com/iklan/images/2025/07/6904_1.jpg",
    },
    {
        no: 6,
        nama: "Sophilia House",
        alamat: "Jalan Danau Tamblingan F1 No 42. Masuk dari Jalan Danau Toba – Pejompongan/Benhil",
        harga: "Rp 2.600.000 per bulan ( 2 juta 600 ribu )",
        tipe: "Wanita",
        kontak: "08151892880",
        fasilitas: "Kamar mandi dalam+ air panas, AC, TV LED, spring bed, jendela kaca udara segar, cuci gosok 2 stel per hari",
        fasUmum: "Dapur, dispenser, kulkas, mesin cuci, wifi",
        ukuran: "3 m x 3 m",
        jumlah: "14 kamar",
        lat: -6.24, lng: 106.805,
        jarakIDX: 1.8,
        tanggal: "2026-06-27",
        narasi: "Khusus cewek Sadon. Yang bikin enak: include cuci gosok 2 stel/hari! Ga perlu mikir laundry. Ada AC, TV LED, KM dalam, air panas, WiFi. Harga 2.6jt. Tapi kamar 3x3 standar dan ga ada info soal parking mobil. Lokasinya Benhil, lumayan deket kantor. Aman buat perempuan.",
        fotos: ["https://kostjakarta.com/iklan/images/2020/01/1229_1.jpg", "https://kostjakarta.com/iklan/images/2020/01/1229_2.jpg", "https://kostjakarta.com/iklan/images/2020/01/1229_3.jpg", "https://kostjakarta.com/iklan/images/2020/01/1229_4.jpg"],
        foto: "https://kostjakarta.com/iklan/images/2020/01/1229_1.jpg",
    },
    {
        no: 7,
        nama: "Dinor Living",
        alamat: "Jalan Danau Towuti E.I No.37 Bendungan Hilir, Jakarta Pusat",
        harga: "Kamar mulai Rp. 2.700.000,- per bulan, Deposit Rp. 1.000.000,-, Listrik token (diisi oleh penyewa)",
        tipe: "Wanita",
        kontak: "087821035555 atau 088299361946",
        fasilitas: "Kamar mandi dalam dilengkapi closet duduk, shower dan wastafel, air conditioner (AC) split, TV LED 24 inch, springbed 2 in 1 ukuran single 100 x 200 cm dan bantal, lemari baju 3 pintu dilengkapi cermin, meja dan kursi kerja, wifi, kunci kamar electro",
        fasUmum: "Ruang tamu dilengkapi TV LED, ruang makan, pantry dilengkapi kompor gas, kulkas 2 pintu, dispenser, ruang cuci, mesin cuci, jemuran dan seterika baju, keamanan 24 jam dilengkapi CCTV, bebas asap rokok",
        ukuran: "3 x 4 m2",
        jumlah: "13",
        lat: -6.24, lng: 106.805,
        jarakIDX: 1.8,
        tanggal: "2025-10-23",
        narasi: "Khusus cewek juga. Modernnya: access card elektronik, kamar dibersihin seminggu sekali, bebas rokok. Tapi water heater bayar tambahan 100rb/bulan, dan laundry harus ke luar (ga ada mesin cuci). Harga 2.7jt + deposit 1jt (lumayan gede depositnya). Kalau Sadon prioritas kebersihan dan keamanan, ini bagus. Kalau mau yang serba include, kurang cocok.",
        fotos: ["https://kostjakarta.com/iklan/images/2024/05/6517_1.jpg", "https://kostjakarta.com/iklan/images/2024/05/6517_2.jpg", "https://kostjakarta.com/iklan/images/2024/05/6517_3.jpg", "https://kostjakarta.com/iklan/images/2024/05/6517_4.jpg"],
        foto: "https://kostjakarta.com/iklan/images/2024/05/6517_1.jpg",
    },
    {
        no: 8,
        nama: "Kost Grand Tebet Suites Co-Living",
        alamat: "Jl Rambutan no 38B. RT 03 / RW 07. Manggarai Selatan, Tebet, Jakarta Selatan",
        harga: ">>> Harga Kamar <<< Yuk pilih kamarmu. Ada 4 tipe Kamar: 1. Royal (3,1jt)Kasur 150 x 200 cm Ukuran kamar 9 m2 Jendela ha",
        tipe: "Pria dan Wanita",
        kontak: "087878595973",
        fasilitas: ">>> 25 Fasilitas Kamar yg akan memanjakan Anda : <<< Android Smart TV 40 inch dengan Dolby Audio Smart TV sudah terhubung dengan Internet _melalui jaringan LAN_ (bukan WiFi), sehingga bisa Streaming Youtube/ Netflix dengan lebih lancar dan puas. Kulk",
        fasUmum: ">>> 11 Fasilitas Umum : <<< GRATIS Air Minum Dispenser RO Yes.. *Hemat uang* utk Air Minum dan tidak perlu sempitin kamar dengan dispenser lagi GRATIS Kopi – Teh – Gula Boost up mood kamu dengan traktiran Kopi dan Teh setiap harinya. Ruang tamu di lt",
        ukuran: "3×4",
        jumlah: "32",
        lat: -6.24, lng: 106.805,
        jarakIDX: 1.8,
        tanggal: "2024-12-02",
        narasi: "Sadon, ini kost paling lengkap di list. WiFi Router PRIBADI per kamar (ga sharing!), kulkas di kamar, Smart TV 40 inch, GRATIS laundry 2 stel/hari, GRATIS room service, kopi-teh tiap hari, Air Fryer, Microwave. Serius kayak hotel. Tapi harganya 3.1-4.3jt dan lokasinya di Tebet (agak jauh, 1.8km). Plus listrik token sendiri. Kalau Sadon ga masalah budget dan mau hidup enak tanpa repot — ini the best.",
        fotos: ["https://kostjakarta.com/iklan/images/2024/12/6722_1.jpg", "https://kostjakarta.com/iklan/images/2024/12/6722_2.jpg", "https://kostjakarta.com/iklan/images/2024/12/6722_3.jpg", "https://kostjakarta.com/iklan/images/2024/12/6722_4.jpg"],
        foto: "https://kostjakarta.com/iklan/images/2024/12/6722_1.jpg",
    },
    {
        no: 9,
        nama: "Griya Amartha",
        alamat: "Jl. Setiabudi Tengah No. 3, Jakarta Selatan 12910",
        harga: "Rp 2.600.000 s.d Rp 3.100.000 per bulan (AC, kamar mandi dalam) Rp 1.5000.000 (non AC, kamar mandi luar)",
        tipe: "Pria / Wanita / Suami-Istri",
        kontak: "082125799198",
        fasilitas: "AC, Internet, Lemari, TV, Tempat Tidur Spring-Bed Premium, Meja dan Kursi, Rak Buku, Telepon Kamar, Balkon pribadi (private balcony), Air Panas, Wastafel, Kamar Mandi Dalam, Pembersihan Kamar (Room Cleaning), Parkir Mobil Luas.",
        fasUmum: "Kamar Mandi Luar, Kitchen / Dapur, Wireless Internet Access, CCTV / 24 Hour Security, Living Room / Ruang Tamu, Dining Room / Ruang Makan, Cleaning Service, Parkir Mobil Luas.",
        ukuran: "4 m x 5 m",
        jumlah: "20",
        lat: -6.2195, lng: 106.827,
        jarakIDX: 2.0,
        tanggal: "2026-06-16",
        narasi: "Kamarnya LUAS Sadon — 4x5m! Ada balkon pribadi, room cleaning, parkir mobil luas. Terasa kayak rumah sendiri. Harga 2.6-3.1jt, di Setiabudi Tengah (2 km ke IDX). Minusnya: listing udah lama dan ga ada info soal WiFi speed. Tapi kalau Sadon butuh space buat WFH atau nyimpen barang banyak, ini paling lega kamarnya.",
        fotos: ["https://www.kostjakarta.com/iklan/images/2020/01/898_1.jpg", "https://www.kostjakarta.com/iklan/images/2020/01/898_2.jpg", "https://www.kostjakarta.com/iklan/images/2020/01/898_3.jpg", "https://www.kostjakarta.com/iklan/images/2020/01/898_4.jpg"],
        foto: "https://www.kostjakarta.com/iklan/images/2020/01/898_1.jpg",
    },
    {
        no: 10,
        nama: "Sun Rise House",
        alamat: "Jl. Setiabudi VI No.45, RT.3/RW.3, Kuningan, Setiabudi, South Jakarta City, Jakarta 12910",
        harga: "Start From Rp 3.500.000 per bulan",
        tipe: "Pria/Wanita/Pasutri",
        kontak: "081586238622",
        fasilitas: "Kamar full furnished. Kamar mandi dalam Water Heater Spring bed ukuran 120 160 cm ( Tergantung Tipe Kamar ) AC TV Cable Working Desk Kursi Lampu belajar Bantal Bed cover",
        fasUmum: "Lobby Swimming Pool Lift Dapur Dispenser Microwave Kulkas Roof top garden Laundry Security 24 jam Finger print untuk akses masuk CCTV di setiap area.",
        ukuran: "4 x 4 m2",
        jumlah: "30",
        lat: -6.2195, lng: 106.827,
        jarakIDX: 2.0,
        tanggal: "2025-08-12",
        narasi: "Premium — ada Swimming Pool, Lift, Rooftop Garden, Fingerprint. Harga mulai 3.5jt. Kamar 4x4m full furnished. Tapi ini kayak mini-apartemen, jadi suasananya impersonal. Dekat MRT dan mall. 2 km ke IDX. Worth it kalau Sadon mau gaya hidup modern, tapi kalau mau yang hangat komunal, ini terlalu 'hotel-ish'.",
        fotos: ["https://www.kostjakarta.com/iklan/images/2021/02/5693_1.jpg", "https://www.kostjakarta.com/iklan/images/2021/02/5693_2.jpg", "https://www.kostjakarta.com/iklan/images/2021/02/5693_3.jpg", "https://www.kostjakarta.com/iklan/images/2021/02/5693_4.jpg"],
        foto: "https://www.kostjakarta.com/iklan/images/2021/02/5693_1.jpg",
    },
    {
        no: 11,
        nama: "PULOR EKSKLUSIF",
        alamat: "Jalan Pulo Raya V No.14, Kebayoran Baru, Jakarta Selatan 12170 (Belakang Kantor Walikota Jakarta Selatan)",
        harga: "Rp 3.500.000 s/d Rp 5.000.000 per bulan",
        tipe: "Pria dan Wanita",
        kontak: "0817804308",
        fasilitas: "Spring Bed Queen Size Merk Florence, TV Samsung/LG LCD 42 inch/ LED 32 inch + TV Langganan First Media, Free Unlimited Internet WiFi 200 Mbps, Kulkas, A/C Split Panasonic 1 PK, Lemari Pakaian, Meja Tulis/Komputer, Kamar Mandi Dalam Air Panas Dingin 2",
        fasUmum: "KARENA LETAK/ LOKASI HUNIAN YANG : REPRESENTATIF & STRATEGIS, akses mudah dan cepat sekitar 10 menit ke Pusat Kota (Jalan Sudirman, Semanggi, Thamrin, Senayan, Gatot Subroto dan sekitarnya) Dekat ke MABES POLRI Trunojoyo Dekat ke beberapa Shopping Ma",
        ukuran: "3m x 5m s/d 5m x 5m",
        jumlah: "10",
        lat: -6.241, lng: 106.7985,
        jarakIDX: 2.2,
        tanggal: "2026-06-27",
        narasi: "Ini favorit ekspatriat Sadon. Kasur Florence, TV 42 inch, WiFi 200Mbps, Air Panas Solahart 24 jam. INCLUDE cuci gosok dan Aqua. Kamar gede (sampai 5x5m). Tapi harga 3.5-5jt — paling mahal di area sini selain Kusuma. Plusnya: parkir luas, lingkungan super tenang (belakang Walikota). Minus: agak jauh dari MRT, lebih cocok kalau Sadon punya motor/mobil.",
        fotos: ["https://www.kostjakarta.com/iklan/images/2020/01/679_1.jpg", "https://www.kostjakarta.com/iklan/images/2020/01/679_2.jpg", "https://www.kostjakarta.com/iklan/images/2020/01/679_3.jpg", "https://www.kostjakarta.com/iklan/images/2020/01/679_4.jpg"],
        foto: "https://www.kostjakarta.com/iklan/images/2020/01/679_1.jpg",
    },
    {
        no: 12,
        nama: "Rumah Kost Exclusive Pulo Raya II no 14",
        alamat: "Jalan Pulo Raya II No. 14, Kebayoran Baru – Jakarta Selatan. Masuk dari Belakang Wali Kota Jakarta Selatan melalui Jalan Nipah atau melalui Jalan Wija",
        harga: "Lantai Bawah Rp 3,100,000. – Luas Kamar Sekitar 24 m2 Lantai Atas Rp 2,900,000. – Luas Kamar Sekitar 18 m2 Lantai atas d",
        tipe: "Pria/Wanita/Suami-Istri",
        kontak: "0812 9252 1240 dan 0812 81816 223",
        fasilitas: "Spring bed dengan ukuran 160 cm nyaman untuk berdua + sprei dan bed cover, kamar mandi di dalam dengan fasilitas air panas, AC 1 PK, TV LED 32 inch dengan TV berlangganan, lemari 2 atau 3 pintu, meja belajar, nakas atau drower (IKEA), WiFi, terase de",
        fasUmum: "Pantry bersama atas dan bawah, kulkas, dispenser air minum, CCTV 24jam.",
        ukuran: "Lantai 1: 24 m2 Lantai 2: 18 m2",
        jumlah: "6",
        lat: -6.241, lng: 106.7985,
        jarakIDX: 2.2,
        tanggal: "2026-04-09",
        narasi: "Kamar GEDE banget Sadon — lantai bawah 24m²! Furniture IKEA, TV langganan. Harga 2.9-3.1jt — value-nya luar biasa buat ukuran segitu. Dekat Pasar Santa dan Blok M (5 menit). Tapi cuma 6 kamar total, jadi kalau penuh ya penuh. Listrik token sendiri. Kalau Sadon dapet kamar di sini, ambil — susah cari kamar seluas ini di harga segitu.",
        fotos: ["https://kostjakarta.com/iklan/images/2020/01/3026_1.jpg", "https://kostjakarta.com/iklan/images/2020/01/3026_2.jpg", "https://kostjakarta.com/iklan/images/2020/01/3026_3.jpg", "https://kostjakarta.com/iklan/images/2020/01/3026_4.jpg"],
        foto: "https://kostjakarta.com/iklan/images/2020/01/3026_1.jpg",
    },
    {
        no: 13,
        nama: "Melawai_Polim_Barito",
        alamat: "Jalan Sungai Sambas 7, Blok M , Kebayoran Baru, Jakarta Selatan 12130",
        harga: "Rp 1.700.000 Rp 2.400.000 Rp 2.700.000",
        tipe: "Pria/Wanita",
        kontak: "081285136677",
        fasilitas: "WiFi Free AC Spring Bed Meja Kursi Lemari pakaian Kamar mandi Shower",
        fasUmum: "Lemari es Air mineral galon Kamar mandi, WC Tempat cuci, jemur.",
        ukuran: "2,5m x 3,0 m2 2,5m x 4,0 m2",
        jumlah: "6",
        lat: -6.244, lng: 106.8005,
        jarakIDX: 2.4,
        tanggal: "2026-02-07",
        narasi: "Paling MURAH di Kebayoran Baru — mulai 1.7jt! Dekat MRT Blok M, TransJakarta, bus bandara. Area tenang, ga banjir. Tapi fasilitasnya basic: AC, WiFi, Spring Bed, KM shower doang. Kamar kecil (2.5x3m). Ga ada laundry, ga ada water heater. Cocok buat Sadon di awal-awal kerja yang mau hemat dulu, nanti pindah kalau udah settle.",
        fotos: ["https://tempat-kost.com/iklan/images/2020/09/2037_1.jpg", "https://tempat-kost.com/iklan/images/2020/09/2037_2.jpg", "https://tempat-kost.com/iklan/images/2020/09/2037_3.jpg", "https://tempat-kost.com/iklan/images/2020/09/2037_4.jpg"],
        foto: "https://tempat-kost.com/iklan/images/2020/09/2037_1.jpg",
    },
    {
        no: 14,
        nama: "AbdiHome Kost Fatmawati Abdi Gandaria Residence",
        alamat: "Jl. Hidup Baru Gang Rumput Hijau No. 47-9, RT. 9 / RW. 6, Gandaria Utara, Kebayoran Baru, Jakarta Selatan 12140",
        harga: "Kamar Non Jendela Tipe A : Rp 2.590.000 Kamar Non Jendela Tipe B: Rp 2.480.000 Kamar Jendela Tipe C : Rp 2.700.000 Kamar",
        tipe: "Campur",
        kontak: "087778500955",
        fasilitas: "AC Kasur Bantal Guling Selimut Lemari/Laci Cermin Meja Kursi Wastafel Shower Closet Duduk Water Heater KM Dalam/KM Luar",
        fasUmum: "Jaringan internet dan sinyal Wifi Dapur Kulkas Dispenser R. Makan R. Jemur Jemuran Mesin Cuci Penjaga Kos CCTV Kartu Akses",
        ukuran: "3 x 3 m",
        jumlah: "15",
        lat: -6.2505, lng: 106.792,
        jarakIDX: 3.5,
        tanggal: "2026-06-20",
        narasi: "Agak jauh Sadon (3.5 km), tapi deket MRT Blok A — bisa MRT ke Istora (IDX) 20 menit, bebas macet. Harga 2.48-2.7jt, fasilitas oke: AC, Water Heater, Mesin Cuci, CCTV, Kartu Akses. Bisa trial mingguan 850rb dulu! Tapi kamar 3x3 standar dan ga ada parkir mobil. Cocok kalau Sadon mau coba-coba dulu sebelum commit bulanan.",
        fotos: ["https://kostjakarta.com/iklan/images/2026/06/7121_1.jpg", "https://kostjakarta.com/iklan/images/2026/06/7121_2.jpg", "https://kostjakarta.com/iklan/images/2026/06/7121_3.jpg", "https://kostjakarta.com/iklan/images/2026/06/7121_4.jpg"],
        foto: "https://kostjakarta.com/iklan/images/2026/06/7121_1.jpg",
    },
    {
        no: 15,
        nama: "Kusuma Kemang Suite",
        alamat: "Jl. Bangka XII No. 6 A Kemang, Mampang Prapatan, Kebayoran Baru – Jakarta Selatan",
        harga: "Rp 5.000.000/Month Rp 2.000.000/Week Rp. 500.000/day",
        tipe: "Pria/Wanita/Suami-Istri",
        kontak: "0813.1144.8769 / 0851-0047.4700",
        fasilitas: "Air conditioning Room, hotel standard bed (included bed sheet, pillow), private bathroom with water heater, Flat LCD TV, lemari baju 2 pintu dan nakas, writing desk + chair + book shelf, WiFi, pre-paid electricity (Room rate is excluding electricity,",
        fasUmum: "Swimming pool, dapur umum (meja, kursi, sofa, kulkas, Aqua, kompor, TV LCD), gazebo, lobby, teras, Wi-Fi, garden, security 24 hours dengan CCTV. Laundry (on request, additional cost). Kamar dibersihkan setiap hari oleh Office Boy.",
        ukuran: "Ukuran Kamar: 4 m x 5 m dan 5 m x 5 m",
        jumlah: "23 Kamar",
        lat: -6.258, lng: 106.8115,
        jarakIDX: 3.7,
        tanggal: "2026-04-27",
        narasi: "Ini basically hotel Sadon. Swimming Pool, Gazebo, Garden, kamar dibersihkan SETIAP HARI. Kamar 4x5m atau 5x5m — super luas. Mayoritas penghuni bule. Tapi harga 5jt/bulan dan paling jauh (3.7 km). Listrik token sendiri juga. Cocok kalau Sadon mau 'treat yourself' atau ada tamu sering dateng. Ga cocok kalau mau hemat.",
        fotos: ["https://www.kostjakarta.com/images2/3871_1.jpg", "https://www.kostjakarta.com/images2/3871_2.jpg", "https://www.kostjakarta.com/images2/3871_3.jpg", "https://www.kostjakarta.com/images2/3871_4.jpg"],
        foto: "https://www.kostjakarta.com/images2/3871_1.jpg",
    },
];

const LANDMARKS = {
    idx: { lat: -6.2246, lng: 106.8097, name: "Gedung IDX (Bursa Efek Indonesia)", area: "SCBD, Jl. Jend. Sudirman Kav 52-53" },
    jisdac: { lat: -6.2355, lng: 106.8234, name: "JISDAC", area: "Jl. Jend. Gatot Subroto, Jakarta Selatan" }
};

const FLOOD_FREE_ZONES = [
    { name: "Setiabudi/Karet", color: "#2a9d8f", coords: [[-6.217,106.823],[-6.217,106.830],[-6.223,106.830],[-6.223,106.823]], desc: "Dekat Gatot Subroto, MRT Setiabudi" },
    { name: "Kebayoran Baru", color: "#e9c46a", coords: [[-6.238,106.796],[-6.238,106.803],[-6.245,106.803],[-6.245,106.796]], desc: "Area Pulo Raya, dekat SCBD" },
    { name: "Tanah Abang/Thamrin", color: "#457b9d", coords: [[-6.206,106.816],[-6.206,106.823],[-6.214,106.823],[-6.214,106.816]], desc: "Dekat MRT, pusat kota" },
];

const FACILITIES = [
    { lat: -6.220, lng: 106.826, type: "makan", name: "Warteg Karet Belakang", zona: "all" },
    { lat: -6.209, lng: 106.819, type: "makan", name: "Street Food Kebon Kacang", zona: "all" },
    { lat: -6.242, lng: 106.800, type: "makan", name: "Bakmi Gajah Mada Melawai", zona: "all" },
    { lat: -6.235, lng: 106.820, type: "makan", name: "Food Court Mampang", zona: "all" },
    { lat: -6.221, lng: 106.828, type: "groceries", name: "Indomaret Karet", zona: "all" },
    { lat: -6.209, lng: 106.820, type: "groceries", name: "Grand Indonesia Mall", zona: "all" },
    { lat: -6.244, lng: 106.801, type: "groceries", name: "Blok M Plaza", zona: "all" },
    { lat: -6.236, lng: 106.818, type: "groceries", name: "Alfamart Tendean", zona: "all" },
    { lat: -6.219, lng: 106.825, type: "laundry", name: "Laundry Express Karet", zona: "all" },
    { lat: -6.243, lng: 106.799, type: "laundry", name: "Quick Wash Melawai", zona: "all" },
    { lat: -6.234, lng: 106.819, type: "laundry", name: "Laundry Tendean", zona: "all" },
];